<?php defined('ABSPATH') || exit; ?>
<?php if($route==='led-ekran-kiralama'): ?>
<section><h2>LED ekran kiralama: etkinlik tarihinden ölçüye.</h2><p>LED ekran kiralama; fuar standı, sahne arka planı, lansman, toplantı ve organizasyonlarda belirli süreli görüntü ihtiyacını karşılamak için değerlendirilir. Rental ekran kabinleri farklı ölçülerde birleştirilir. Uygun sistem, etkinlik tarihi ve kullanım alanı netleştiğinde seçilir. Stok ve ekip uygunluğu teklif aşamasında teyit edilir.</p></section>
<section><h2>Sahne ve fuar LED ekran kiralama</h2><p>Sahne LED ekran kiralama işinde askı, zemin desteği, yenileme hızı ve kamera çekimi birlikte planlanır. Fuar LED ekran kiralama işinde ise stand yüksekliği, izleme mesafesi ve kurulum süresi öne çıkar. Her iki senaryoda da <a href="<?php echo rle_link('rental-led-ekran'); ?>">rental LED ekran</a> ve <a href="<?php echo rle_link('air-star'); ?>">AIR / STAR</a> başlangıç noktalarıdır.</p></section>
<section><h2>Kiralama talebinde hangi bilgiler gerekir?</h2><ul><li>Etkinlik tarihi, kurulum ve söküm için uygun saatler.</li><li>Şehir, ilçe, mekân ve iç/dış ortam bilgisi.</li><li>Ekranın hedef genişliği, yüksekliği ve izleme mesafesi.</li><li>Görüntü kaynağı: bilgisayar, kamera, sunum veya video oynatıcı.</li><li>Askı, zemin desteği, taşıyıcı yapı ve teknik operatör ihtiyacı.</li></ul><p>İstanbul öncelikli olmak üzere Türkiye genelindeki taleplerinizde mekân erişimi, nakliye ve ekip planlamasını birlikte değerlendirelim. <a href="<?php echo rle_link('istanbul-led-ekran'); ?>">İstanbul LED ekran kiralama</a> sayfasında ilçe ve keşif notlarını okuyabilirsiniz.</p></section>
<section><h2>LED ekran kiralama fiyatı yalnızca alan değildir.</h2><p>Ekran ölçüsü ve modeli, kiralama süresi, şehir, kurulum biçimi ve teknik destek kapsamı fiyatı etkiler. Aynı tarih için alınan teklifleri karşılaştırırken nakliye, kurulum, söküm ve operatör kalemlerini ayrı ayrı kontrol edin. Güncel uygunluk ve kapsam olmadan sabit fiyat vermek doğru olmaz. Ayrıntı için <a href="<?php echo rle_link('led-ekran-fiyatlari'); ?>">LED ekran fiyatları</a> rehberine bakın.</p></section>
<section><h2>Satın alma mı, kiralama mı?</h2><p>Tek etkinlik veya belirli süreli kullanım için kiralama; düzenli kullanım ve kalıcı kurulum için <a href="<?php echo rle_link('led-ekran-satisi'); ?>">LED ekran satışı</a> teklifini değerlendirin. Toplam kullanım süresi, taşıma, bakım ve operasyon ihtiyacını birlikte karşılaştırın.</p></section>
<section class="article-callout"><h2>Etkinliğinizi anlatarak başlayın.</h2><p>Teklif formunda “Kiralama talebi”ni seçin. Tarihi ve kullanım süresini proje notuna ekleyin; ölçü, mekân ve şehir bilgisini belirtin.</p><a class="button" href="<?php echo esc_url(add_query_arg('talep','kiralama',rle_navigation_url('iletisim'))); ?>#planlayici">LED ekran kiralama teklifi ↗</a></section>
<?php rle_render_faq('led-ekran-kiralama'); ?>
<?php elseif($route==='led-ekran-satisi'): ?>
<section><h2>LED ekran satışı kalıcı yatırım içindir.</h2><p>LED ekran satışı; mağaza, lobi, toplantı salonu, vitrin ve sabit sahne alanlarında düzenli kullanım için planlanır. Satın alma teklifi piksel aralığı, kabin, kontrol sistemi, montaj ve servis kapsamıyla yazılır. Kısa süreli etkinliklerde <a href="<?php echo rle_link('led-ekran-kiralama'); ?>">LED ekran kiralama</a> daha uygun olabilir.</p></section>
<section><h2>LED ekran satın alırken bakılacaklar</h2><ol class="editorial-list"><li><h3>İzleme mesafesi ve içerik</h3><p>Yakın yazı ve sunum için daha sık piksel; sahne arka planında rental veya AIR kabinler değerlendirilir.</p></li><li><h3>İç veya dış mekân</h3><p>Parlaklık ve koruma model belgesinden kontrol edilir. Vitrin camının arkasında bile güneş yönü belirtilmelidir.</p></li><li><h3>Bakım erişimi</h3><p>Arkası kapalı duvarlarda Front serisi; yakın izlemede COB; cam yüzeyde transparan LED incelenir.</p></li></ol></section>
<section><h2>İstanbul’dan Türkiye geneline satış</h2><p>Rental Ekran iletişim noktası Şişli’dedir. İstanbul LED ekran satışı projelerinde yerinde ölçü planlanabilir. Diğer şehirlerde fotoğraf, plan ve nakliye kapsamı teklifte netleşir. Ürün ailesini <a href="<?php echo rle_link('urunlerimiz'); ?>">LED ekran modelleri</a> sayfasından karşılaştırın.</p></section>
<section class="article-callout"><h2>Satış teklifi için ölçü yeter.</h2><p>Hedef genişlik, yükseklik, en yakın izleyici ve mekân fotoğrafını paylaşın. Formda talep türünü “Satın alma / proje teklifi” seçin.</p><a class="button" href="<?php echo rle_link('iletisim'); ?>#planlayici">LED ekran satış teklifi ↗</a></section>
<?php rle_render_faq('led-ekran-satisi'); ?>
<?php elseif($route==='istanbul-led-ekran'): ?>
<section><h2>İstanbul LED ekran kiralama ve satış.</h2><p>Rental Ekran’ın iletişim noktası İstanbul Şişli’dedir. İstanbul LED ekran kiralama ve satış taleplerinizi sahne, fuar, mağaza ve kurumsal alanlara göre değerlendiriyoruz.</p><p><?php echo esc_html($settings['address']); ?> adresiyle ilgili ziyaret planınızı önceden telefonla netleştirebilirsiniz. <a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/','',$settings['phone'])); ?>"><?php echo esc_html($settings['phone']); ?></a></p></section>
<section><h2>İstanbul projelerinde teklifi hızlandıran bilgiler</h2><p>Mekânın ilçesini, ekranın yerleşeceği alanı, yükleme/boşaltma imkânını ve kurulum saatlerini belirtin. Etkinlik alanlarında teknik giriş kuralları ve elektrik hazırlığı; mağaza ve ofislerde montaj yüzeyi ve bakım erişimi planı etkiler.</p><p>Vitrin için <a href="<?php echo rle_link('transparan-led-ekran'); ?>">transparan LED</a>, yakın izleme alanı için <a href="<?php echo rle_link('cob'); ?>">COB</a>, etkinlik için <a href="<?php echo rle_link('led-ekran-kiralama'); ?>">kiralama seçeneklerini</a> inceleyebilirsiniz.</p></section>
<section><h2>Türkiye genelinden proje talepleri</h2><p>İstanbul dışındaki taleplerde şehir, proje tarihi ve mekân bilgisiyle başlayın. Nakliye, kurulum, teknik destek ve teslim kapsamını konuma ve proje koşullarına göre teklifte netleştirelim. İl bazında şube veya aynı gün teslimat taahhüdü vermiyoruz; her talep kendi kapsamıyla değerlendirilir.</p></section>
<section class="article-callout"><h2>Satış ve kiralama için tek iletişim noktası.</h2><p>Ölçü ve kullanım alanını paylaşın; seçilecek model ile teklif kapsamını birlikte belirleyelim.</p><a class="button" href="<?php echo rle_link('iletisim'); ?>#planlayici">Proje talebi hazırlayın ↗</a></section>
<?php rle_render_faq('istanbul-led-ekran'); ?>
<?php elseif($route==='led-ekran-fiyatlari'): ?>
<section><h2>Tek başına metrekare fiyatı yeterli değildir.</h2><p>Aynı ölçüde iki LED ekran; piksel aralığı, kabin yapısı, kontrol sistemi ve montaj kapsamı nedeniyle farklı fiyatlandırılabilir. Karşılaştırma yaparken tekliflerin aynı teknik ve hizmet kapsamına sahip olduğundan emin olun.</p><p>Bu sayfada güncel birim fiyat listesi yerine teklif hazırlığını etkileyen unsurları bulabilirsiniz. Model, kapsam ve güncel tedarik koşulları netleşmeden sayısal fiyat vermek yanıltıcı olabilir.</p></section>
<section><h2>Fiyatı belirleyen altı başlık</h2><ol class="editorial-list"><li><h3>Ekran ölçüsü ve kabin adedi</h3><p>Hedef genişlik ve yükseklik tam kabin ölçülerine uymayabilir. Gerçek ekran boyutunu ve kabin sayısını teklifte açıkça isteyin.</p></li><li><h3>Piksel aralığı ve hedef çözünürlük</h3><p>Aynı yüzeyde daha küçük piksel aralığı daha çok piksel anlamına gelir. Yakın izleme ve küçük yazı ihtiyacınız yoksa yalnızca en küçük piksel aralığına yönelmek doğru karşılaştırmayı zorlaştırabilir.</p></li><li><h3>İç veya dış mekân gereksinimi</h3><p>Parlaklık, kabin koruması ve bağlantılar ortama uygun seçilmelidir. Vitrin camının arkasındaki ekranlarda bile güneş yönünü belirtin.</p></li><li><h3>Kontrol sistemi ve görüntü kaynakları</h3><p>Bilgisayar, kamera veya medya oynatıcı gibi kaynakları listeleyin. Giriş portları, işlemci kapasitesi ve içerik yönetimi teklif kapsamına yazılmalıdır.</p></li><li><h3>Montaj ve taşıyıcı yapı</h3><p>Duvar, askı, zemin veya taşınabilir kurulum farklı kapsamlar gerektirir. Taşıyıcı yapı, kablolama, elektrik hazırlığı ve nakliyeyi ayrı kalemlerle değerlendirin.</p></li><li><h3>Bakım ve teslim kapsamı</h3><p>Yedek modül, eğitim, kurulum, garanti koşulları ve servis kapsamını yazılı olarak isteyin. İki teklifin aynı hizmetleri içerdiğini kontrol edin.</p></li></ol></section>
<section class="article-callout"><h2>Teklif istemeden önce hazır edin</h2><p>Ekranın genişliği ve yüksekliği, en yakın izleyici mesafesi, mekân fotoğrafı, içerik türü, kurulum şekli ve hedef tarih. Böylece model seçimi ve kapsam daha hızlı netleşir.</p><a class="button" href="<?php echo rle_link('iletisim'); ?>#planlayici">Teklif taslağını hazırlayın ↗</a></section>
<?php rle_render_faq('led-ekran-fiyatlari'); ?>
<?php elseif($route==='led-ekran-secim-rehberi'): ?>
<section><h2>1. Ekranda ne gösterilecek?</h2><p>Video ağırlıklı sahne arka planıyla küçük yazı içeren toplantı sunumu aynı ihtiyaç değildir. İzlenecek içerikten örnek hazırlayın. Yazı boyutu, grafik yoğunluğu ve kamera çekimi planı ürün seçimini etkiler.</p></section>
<section><h2>2. En yakın izleyici nerede?</h2><p>Piksel aralığı, komşu pikseller arasındaki mesafeyi milimetre olarak ifade eder. Daha küçük aralık aynı ölçüde daha fazla piksel sağlar. Tek bir mesafe kuralıyla kesin model seçmek yerine içerik, izleme mesafesi ve bütçeyi birlikte değerlendirin.</p><p>Yakın izleme projelerinde <a href="<?php echo rle_link('cob'); ?>">COB serisini</a>, taşınabilir etkinlik sistemlerinde <a href="<?php echo rle_link('rental-led-ekran'); ?>">Rental LED ekranları</a> başlangıç noktası olarak inceleyebilirsiniz.</p></section>
<section><h2>3. Sabit mi, tekrar kurulacak mı?</h2><p>Sık kurulumda kabin ağırlığı, kilit sistemi, taşıma ve bağlantılar öne çıkar. Sabit projede bakım erişimi, taşıyıcı yapı ve hava akışı baştan planlanmalıdır. <a href="<?php echo rle_link('air-star'); ?>">AIR / STAR</a> ve <a href="<?php echo rle_link('front'); ?>">Front</a> serilerini bu gereksinimlerle karşılaştırın.</p></section>
<section><h2>4. Ekran ölçüsünü çözünürlükle birlikte düşünün</h2><p>İlk yaklaşım olarak yatay piksel sayısı, ekran genişliğinin milimetre cinsinden piksel aralığına bölünmesiyle tahmin edilir. Örneğin 4.000 mm genişlik ve 2,5 mm piksel aralığı yaklaşık 1.600 piksel verir. Gerçek çözünürlük seçilen modül ve tam kabin yerleşiminden hesaplanmalıdır.</p><p>Sunum kaynağınızın en-boy oranıyla ekran oranını karşılaştırın; aksi hâlde kırpma veya boş alan oluşabilir.</p></section>
<section><h2>5. Özel yüzeyleri ayrıca değerlendirin</h2><p>Cam yüzeylerde <a href="<?php echo rle_link('transparan-led-ekran'); ?>">transparan ekran</a>, zemin uygulamalarında <a href="<?php echo rle_link('floor'); ?>">Floor</a>, yüzey koruması gereken alanlarda <a href="<?php echo rle_link('gob'); ?>">GOB</a> ailesi incelenebilir. Bu adlar tek başına IP koruması, yük kapasitesi veya interaktif kullanım garantisi vermez.</p></section>
<section class="article-callout"><h2>Seçim kontrol listesi</h2><ul><li>İçerik örneği ve kaynak cihazlar belli mi?</li><li>Ölçü, en yakın izleyici ve güneş yönü net mi?</li><li>Bakım erişimi ve kurulum yöntemi planlandı mı?</li><li>Model belgesi, garanti ve teklif kapsamı yazılı mı?</li></ul><a class="button" href="<?php echo rle_link('iletisim'); ?>">Projenizi paylaşın ↗</a></section>
<?php else: ?>
<section><h2>Mekânı yalnızca “içerisi” ve “dışarısı” diye ayırmayın.</h2><p>Açık hava uygulamasında yağış, toz, güneş, sıcaklık ve rüzgâr birlikte değerlendirilir. İç mekânda ise ortam ışığı, izleyici yakınlığı ve bakım erişimi öne çıkabilir. Vitrin içindeki bir ekran, kapalı alanda bulunmasına rağmen yoğun güneş alabilir.</p></section>
<section><h2>Karşılaştırılacak temel kriterler</h2><div class="table-scroll" role="region" aria-label="İç ve dış mekân ekran kriterleri" tabindex="0"><table><thead><tr><th scope="col">Kriter</th><th scope="col">İç mekân</th><th scope="col">Dış mekân</th></tr></thead><tbody><tr><th scope="row">Parlaklık</th><td>Ortam aydınlığı ve izleyici konforu</td><td>Güneş altında görünürlük ve gece ayarı</td></tr><tr><th scope="row">Koruma</th><td>Toz, temas ve alanın koşulları</td><td>Ön/arka yüz ve bağlantıların belgelenmiş koruması</td></tr><tr><th scope="row">Montaj</th><td>Bakım mesafesi, duvar veya askı erişimi</td><td>Hava koşulları ve taşıyıcı yapı değerlendirmesi</td></tr><tr><th scope="row">İçerik</th><td>Yakından izlenen metin ve sunumlar</td><td>İzleme mesafesine uygun yazı ve görseller</td></tr></tbody></table></div></section>
<section><h2>IP derecesini model belgesinden kontrol edin.</h2><p>Bir ürün ailesinin adı tüm modellerin aynı korumaya sahip olduğunu göstermez. Ön ve arka yüz dereceleri farklı olabilir. Kabin kadar güç ve sinyal bağlantıları ile kurulum biçimi de değerlendirilmelidir. GOB kaplama veya “rental” tanımı tek başına dış mekân uygunluğunu kanıtlamaz.</p></section>
<section><h2>Model seçimine nereden başlayabilirsiniz?</h2><p>Taşınabilir kurulumlarda <a href="<?php echo rle_link('rental-led-ekran'); ?>">rental LED</a> ve <a href="<?php echo rle_link('air-star'); ?>">AIR serilerinin</a> iç/dış mekân seçeneklerini inceleyin. Cam yüzeylerde <a href="<?php echo rle_link('transparan-led-ekran'); ?>">transparan LED ekranı</a> parlaklık, şeffaflık ve güneş yönüyle değerlendirin.</p></section>
<section class="article-callout"><h2>Mekân bilgisi teklifi iyileştirir.</h2><p>Gün ışığında çekilmiş mekân fotoğrafları, montaj yüksekliği, izleme yönü ve planlanan ekran ölçüsünü paylaşın. Teknik uygunluk bu bilgilerle model bazında kontrol edilebilir.</p><a class="button" href="<?php echo rle_link('iletisim'); ?>">İhtiyaçlarınızı iletin ↗</a></section>
<?php endif; ?>
