<?php
defined('ABSPATH') || exit;
$route=rle_route(); $page=rle_routes()[$route]; $product=rle_product($route); $settings=rle_settings();
function rle_cards() {
    foreach(rle_products() as $i=>$p) { ?>
    <a class="product-card" href="<?php echo rle_link($p['slug']); ?>">
        <div class="card-visual"><?php if(!empty($p['image'])): ?><img src="<?php echo esc_url(RLE_URL.$p['image']); ?>" alt="<?php echo esc_attr($p['name'].' ürün görünümü'); ?>" loading="lazy" decoding="async" width="720" height="480"><?php else: ?><div class="glass-demo" aria-label="Transparan ekranı anlatan temsili şema"><span>GÖRÜNÜR<br>OLUN.</span><small>Temsili şema</small></div><?php endif; ?><span class="card-index"><?php echo esc_html(sprintf('%02d',$i+1)); ?></span></div>
        <div class="card-copy"><p class="eyebrow"><?php echo esc_html($p['tag']); ?></p><h3><?php echo esc_html($p['name']); ?><span aria-hidden="true">↗</span></h3><p><?php echo esc_html($p['intro']); ?></p><span class="text-link">Seriyi inceleyin <span aria-hidden="true">→</span></span></div>
    </a><?php } ?>
    <a class="product-card" href="https://drive.google.com/file/d/17NBv7dyLgH8kbWdPiN_vM-fTWF9a3VF5/view" target="_blank" rel="noopener"><div class="card-visual"><div class="glass-demo"><span>STADIUM<br>SCREEN</span><small>Ürün dokümanı</small></div><span class="card-index">08</span></div><div class="card-copy"><p class="eyebrow">STADYUM · GENİŞ ALAN</p><h3>Stadium Screen <span aria-hidden="true">↗</span></h3><p>Stadyum ve geniş alan uygulamaları için teknik dokümana erişin.</p><span class="text-link">Dokümanı inceleyin <span aria-hidden="true">→</span></span></div></a><?php
}
function rle_guides() { ?>
<section class="section guides"><div class="section-heading"><div><p class="eyebrow">KARAR VERMEDEN ÖNCE</p><h2>Doğru sorular, doğru ekran.</h2></div><p>Ürün adından başlayıp projenizin gerçek ihtiyacına ulaşın.</p></div><div class="guide-grid">
<?php foreach(array('led-ekran-secim-rehberi'=>'01 / SEÇİM','led-ekran-fiyatlari'=>'02 / BÜTÇE','ic-mekan-dis-mekan-led-ekran'=>'03 / KULLANIM ORTAMI') as $slug=>$label): ?>
<a class="guide-card" href="<?php echo rle_link($slug); ?>"><span class="eyebrow"><?php echo esc_html($label); ?></span><h3><?php echo esc_html(rle_routes()[$slug]['name']); ?></h3><span aria-hidden="true">↗</span></a><?php endforeach; ?></div></section><?php }
function rle_cta() { ?>
<section class="project-cta"><div><p class="eyebrow">BİR EKRANDAN FAZLASI</p><h2>Ölçüyü siz verin.<br>Seçenekleri birlikte netleştirelim.</h2></div><a class="button light" href="<?php echo rle_link('led-ekran-teklif'); ?>">Projeniz için teklif isteyin <span aria-hidden="true">↗</span></a></section><?php }
function rle_legacy_details($slug, $skip_images=false) {
    $content=rle_legacy_content($slug);
    if (!$skip_images && !empty($content['images'])): ?><section class="section legacy-gallery rle-stagger"><div class="section-heading"><div><p class="eyebrow">ÜRÜN GÖRSELLERİ</p><h2>Uygulama ve kabin detayları.</h2></div><p>Seçilen ürün ailesine ait referans görseller; proje planlamasında ölçek ve montaj fikri verir.</p></div><div class="legacy-image-grid"><?php foreach($content['images'] as $image): ?><figure class="rle-reveal"><img src="<?php echo esc_url($image['src']); ?>" alt="<?php echo esc_attr($image['alt'] ?: 'Rental Ekran ürün görseli'); ?>" loading="lazy" decoding="async"><figcaption><?php echo esc_html($image['alt']); ?></figcaption></figure><?php endforeach; ?></div></section><?php endif;
    if (!empty($content['tables'])): ?><section class="section legacy-tables"><div class="section-heading"><div><p class="eyebrow">TEKNİK TABLOLAR</p><h2>Model ve kabin verileri.</h2></div><p>Piksel aralığı, kabin ölçüsü ve kontrol seçenekleri; teklif öncesi karşılaştırma için.</p></div><?php foreach($content['tables'] as $table): ?><div class="table-scroll" tabindex="0" role="region" aria-label="Teknik özellik tablosu"><table><tbody><?php foreach($table as $row): ?><tr><?php foreach($row as $i=>$cell): ?><?php if($i===0): ?><th scope="row"><?php echo esc_html($cell); ?></th><?php else: ?><td><?php echo esc_html($cell); ?></td><?php endif; ?><?php endforeach; ?></tr><?php endforeach; ?></tbody></table></div><?php endforeach; ?></section><?php endif;
    if (!empty($content['sections'])): ?><section class="section detail-blocks rle-stagger"><div class="section-heading"><div><p class="eyebrow">TEKNİK DETAYLAR</p><h2>Kullanım senaryoları ve avantajlar.</h2></div></div><div class="detail-block-grid"><?php foreach($content['sections'] as $i=>$section): ?><article class="detail-block rle-reveal"><span class="detail-index"><?php echo esc_html(sprintf('%02d',$i+1)); ?></span><h3><?php echo esc_html($section['title']); ?></h3><?php foreach($section['text'] as $text): ?><p><?php echo esc_html($text); ?></p><?php endforeach; ?></article><?php endforeach; ?></div></section><?php endif;
}
function rle_product_slider($product, $slug) {
    $slides=array();
    if (!empty($product['image'])) $slides[]=array('src'=>RLE_URL.$product['image'],'alt'=>$product['name'].' ürün görünümü');
    $legacy=rle_legacy_content($slug);
    foreach (!empty($legacy['images']) ? $legacy['images'] : array() as $image) if (!empty($image['src'])) $slides[]=array('src'=>$image['src'],'alt'=>!empty($image['alt']) ? $image['alt'] : $product['name'].' ürün görseli');
    $seen=array(); $slides=array_values(array_filter($slides,function($slide) use (&$seen) { if(isset($seen[$slide['src']])) return false; $seen[$slide['src']]=true; return true; }));
    if (empty($slides)) { ?><div class="product-image"><div class="glass-demo"><span>GÖRÜNÜR<br>OLUN.</span><small>Transparan ekran / temsili şema</small></div></div><?php return; }
    ?><section class="product-slider" data-rle-slider aria-label="<?php echo esc_attr($product['name'].' ürün görselleri'); ?>"><div class="product-slider-track"><?php foreach($slides as $i=>$slide): ?><figure class="product-slider-slide"<?php if($i>0): ?> hidden<?php endif; ?>><img src="<?php echo esc_url($slide['src']); ?>" alt="<?php echo esc_attr($slide['alt']); ?>"<?php if($i===0): ?> fetchpriority="high"<?php else: ?> loading="lazy"<?php endif; ?> width="960" height="640"></figure><?php endforeach; ?></div><?php if(count($slides)>1): ?><div class="product-slider-controls"><button class="slider-button" type="button" data-slider-prev aria-label="Önceki görsel">←</button><span class="slider-count" data-slider-count>1 / <?php echo esc_html(count($slides)); ?></span><button class="slider-button" type="button" data-slider-next aria-label="Sonraki görsel">→</button></div><div class="slider-dots" role="tablist" aria-label="Ürün görselleri"><?php foreach($slides as $i=>$slide): ?><button type="button" data-slider-dot="<?php echo esc_attr($i); ?>" aria-label="<?php echo esc_attr(($i+1).'. görsel'); ?>"<?php if($i===0): ?> aria-current="true"<?php endif; ?>></button><?php endforeach; ?></div><?php endif; ?></section><?php
}
?>
<?php rle_render_shell_open(); ?>
<?php if($route!==''): ?><nav class="breadcrumbs wrap" aria-label="İçerik yolu"><a href="<?php echo rle_link(''); ?>">Ana sayfa</a><span aria-hidden="true">/</span><span aria-current="page"><?php echo esc_html($page['name']); ?></span></nav><?php endif; ?>
<?php if($route===''): ?>
<section class="hero wrap"><div class="hero-copy"><p class="eyebrow"><span class="red-dot"></span> LED EKRAN SATIŞ VE KİRALAMA · İSTANBUL</p><h1>LED ekran<br><em>satış ve kiralama.</em></h1><p class="hero-intro">Sahne, fuar, vitrin ve kurumsal mekânlar için LED ekran satışı veya rental ekran kiralama. Ölçü, piksel ve mekâna göre teklif hazırlarız.</p><div class="actions"><a class="button" href="<?php echo esc_url(rle_legacy_url('urunlerimiz')); ?>">LED ekranları keşfedin <span aria-hidden="true">↗</span></a><a class="text-link" href="<?php echo rle_link('led-ekran-teklif'); ?>#planlayici">Ekranınızı planlayın →</a></div><div class="hero-note"><span>01—07</span><p>Rental · Front · AIR / STAR · COB<br>GOB · Floor · Transparan</p></div></div><div class="hero-visual"><div class="visual-top"><span>MODÜLER LED SİSTEMLER</span><span>RE / 01</span></div><img src="<?php echo esc_url(RLE_URL.'assets/rental-led-ekran.webp'); ?>" alt="Rental LED ekran modüler kabin ve bağlantı yapısı" width="960" height="640" fetchpriority="high"><div class="visual-bottom"><div><span class="eyebrow">İHTİYACA GÖRE YAPILANDIRMA</span><strong>Tek ekran. Birçok olasılık.</strong></div><a href="<?php echo esc_url(rle_legacy_url('rental-led-ekran')); ?>" aria-label="Rental LED ekran serisini incele">↗</a></div></div></section>
<div class="benefit-strip"><span><b>01</b> Kullanım alanına göre seçim</span><span><b>02</b> Model bazında teknik değerlendirme</span><span><b>03</b> Projeye özel teklif</span></div>
<section class="section wrap"><div class="section-heading"><div><p class="eyebrow">İSTANBUL MERKEZLİ · TÜRKİYE GENELİ PROJELER</p><h2>Satın alın ya da kiralayın.</h2></div><p>Kalıcı ekran yatırımınızı veya etkinlik için geçici ekran ihtiyacınızı ayrı kapsamlarla planlıyoruz.</p></div><div class="service-grid"><a class="guide-card" href="<?php echo esc_url(rle_legacy_url('urunlerimiz')); ?>"><span class="eyebrow">LED EKRAN SATIŞI</span><h3>İşinize uygun ekran yatırımı.</h3><p>Ürün ailesi, piksel aralığı, kontrol sistemi ve montaj kapsamına göre satış teklifi.</p><span aria-hidden="true">↗</span></a><a class="guide-card" href="<?php echo rle_link('led-ekran-kiralama'); ?>"><span class="eyebrow">LED EKRAN KİRALAMA</span><h3>Etkinliğinize uygun görüntü.</h3><p>Fuar, sahne ve lansmanlar için tarih, kullanım süresi ve mekâna göre kiralama teklifi.</p><span aria-hidden="true">↗</span></a></div><p class="region-note">Şişli, İstanbul’daki iletişim noktamızdan <a class="text-link" href="<?php echo rle_link('istanbul-led-ekran'); ?>">İstanbul projelerinizi</a> ve Türkiye genelindeki taleplerinizi değerlendiriyoruz. Nakliye, kurulum ve teknik destek kapsamı projenin şehrine ve koşullarına göre teklifte netleştirilir.</p></section>
<section class="section wrap"><div class="section-heading"><div><p class="eyebrow">ÜRÜN KOLEKSİYONU</p><h2>Her alanın ihtiyacı farklı.</h2></div><p>Taşınabilir sahne sistemlerinden yakın izleme ekranlarına: projenizin başlangıç noktasını seçin.</p></div><div class="product-grid"><?php rle_cards(); ?></div></section>
<div class="wrap"><?php rle_guides(); rle_cta(); ?></div>
<?php elseif($route==='urunlerimiz'): ?>
<section class="page-intro wrap"><p class="eyebrow">ÜRÜN KOLEKSİYONU / 8 BAŞLIK</p><h1>LED ekran modelleri.</h1><p>LED ekran satışı veya kiralama için önce kullanım alanını belirleyin. Ardından piksel aralığını, kabin yapısını ve bakım erişimini birlikte değerlendirin.</p></section><section class="wrap section compact"><div class="product-grid"><?php rle_cards(); ?></div></section>
<section class="section wrap"><div class="section-heading"><h2>Hangi aile, hangi ihtiyaç?</h2></div><div class="table-scroll" tabindex="0" role="region" aria-label="LED ekran ailesi karşılaştırması"><table><caption>Ürün ailesine göre ilk değerlendirme</caption><thead><tr><th scope="col">Ürün ailesi</th><th scope="col">Başlangıç ihtiyacı</th><th scope="col">Teklifte sorulacak konu</th></tr></thead><tbody><?php foreach(rle_products() as $p): ?><tr><th scope="row"><a href="<?php echo rle_link($p['slug']); ?>"><?php echo esc_html($p['name']); ?></a></th><td><?php echo esc_html($p['uses'][0]); ?></td><td><?php echo esc_html($p['specs'][2][1]); ?></td></tr><?php endforeach; ?></tbody></table></div></section><div class="wrap"><?php rle_cta(); ?></div>
<?php elseif($product): ?>
<section class="product-hero wrap"><div><p class="eyebrow"><?php echo esc_html($product['tag']); ?></p><h1><?php echo esc_html($product['name']); ?></h1><p class="lead"><?php echo esc_html($product['intro']); ?></p><p><?php echo esc_html($product['body']); ?></p><div class="actions"><a class="button" href="<?php echo esc_url(add_query_arg('urun',$product['slug'],rle_navigation_url('iletisim'))); ?>#planlayici">Bu ürün için teklif isteyin ↗</a><a class="text-link" href="#teknik">Teknik özeti inceleyin ↓</a></div></div><?php rle_product_slider($product, $route); ?></section>
<section id="teknik" class="section wrap product-details"><div><p class="eyebrow">ÜRÜNÜ TANIYIN</p><h2>Teknik başlangıç noktası.</h2><p>Bu özet ürün ailesini seçmenize yardımcı olur. Kesin teknik değerler, seçilen model ve güncel üretici belgesiyle teklif aşamasında doğrulanır.</p><h3>Değerlendirilebilecek kullanım alanları</h3><ul class="check-list"><?php foreach($product['uses'] as $use): ?><li><?php echo esc_html($use); ?></li><?php endforeach; ?></ul></div><div><dl class="spec-list"><?php foreach($product['specs'] as $spec): ?><div><dt><?php echo esc_html($spec[0]); ?></dt><dd><?php echo esc_html($spec[1]); ?></dd></div><?php endforeach; ?></dl></div></section>
<div class="wrap"><?php rle_legacy_details($route, true); ?></div>
<section class="section wrap faq"><p class="eyebrow">SIK SORULANLAR</p><h2>Seçimden önce netleştirin.</h2><?php foreach($product['questions'] as $qa): ?><details><summary><?php echo esc_html($qa[0]); ?></summary><p><?php echo esc_html($qa[1]); ?></p></details><?php endforeach; ?></section>
<div class="wrap"><?php rle_guides(); rle_cta(); ?></div>
<?php elseif($route==='led-ekran-teklif' || $route==='iletisim'): ?>
<section class="page-intro wrap"><p class="eyebrow">PROJENİZ BURADA BAŞLAR</p><h1>LED ekran teklifi alın.</h1><p>LED ekran kiralama veya satış için ölçü, şehir ve iletişim bilgilerinizi gönderin. Talep e-posta kutumuza düşer; dilerseniz WhatsApp taslağını da açabilirsiniz.</p></section>
<section class="wrap contact-layout" id="planlayici"><div class="planner" data-wa="<?php echo esc_attr($settings['whatsapp']); ?>" data-email="<?php echo esc_attr($settings['email']); ?>"><p class="eyebrow">PROJE PLANLAYICI</p><h2>Ekranınızın ilk taslağı.</h2><?php rle_contact_notice(); ?><form id="rle-planner-form" method="post" action="<?php echo rle_link($route); ?>#planlayici"><?php wp_nonce_field('rle_contact'); ?><input type="hidden" name="rle_contact" value="1"><p class="rle-hp" hidden><label>Website<input name="rle_website" tabindex="-1" autocomplete="off"></label></p><div class="form-grid"><label>Adınız<input name="contact_name" required maxlength="80" autocomplete="name"></label><label>Telefon<input name="contact_phone" required maxlength="30" autocomplete="tel" inputmode="tel"></label><label class="full">E-posta<input name="contact_email" type="email" required maxlength="120" autocomplete="email"></label><label>İlgilendiğiniz ürün<select name="product" id="rle-product"><?php foreach(rle_products() as $p): ?><option value="<?php echo esc_attr($p['slug']); ?>"><?php echo esc_html($p['name']); ?></option><?php endforeach; ?><option value="kararsiz">Seçim için destek istiyorum</option></select></label><label>Talep türü<select name="request"><option>Satın alma / proje teklifi</option><?php if($settings['business_mode']!=='project'): ?><option <?php selected($settings['business_mode'],'rental'); ?>>Kiralama talebi</option><?php endif; ?><option>Teknik bilgi</option></select></label><label>Kullanım ortamı<select name="environment"><option>İç mekân</option><option>Dış mekân</option><option>Vitrin / cam yüzey</option><option>Henüz net değil</option></select></label><label>Şehir / ilçe<input name="city" maxlength="100" placeholder="Örn. İstanbul / Şişli" autocomplete="address-level2"></label><label>Hedef genişlik (metre)<input name="width" type="number" min="0.1" max="100" step="0.01" value="4" required inputmode="decimal"></label><label>Hedef yükseklik (metre)<input name="height" type="number" min="0.1" max="100" step="0.01" value="3" required inputmode="decimal"></label><label>Örnek kabin ölçüsü<select name="cabinet"><option value="0.5,0.5">500 × 500 mm</option><option value="0.5,1">500 × 1000 mm</option></select></label><label>En yakın izleme mesafesi<input name="distance" maxlength="50" placeholder="Örn. 3 metre"></label><label class="full">Proje notu<textarea name="note" maxlength="1000" rows="3" placeholder="Kullanım amacı, tarih ve içerik türü…"></textarea></label></div><p class="small muted">Kabin hesabı örnek yerleşim içindir; seçtiğiniz ürünün ölçüsü ve montaj projesiyle doğrulanmalıdır. Fiyat veya mühendislik projesi oluşturmaz.</p><div class="actions"><button class="button" id="rle-send" type="submit">Talebi e-posta ile gönder →</button><button class="text-link" id="rle-generate" type="button">WhatsApp taslağı hazırla</button></div></form>
<div id="rle-result" class="planner-result" hidden><h3>Örnek kabin yerleşimi</h3><p id="rle-calculation" role="status" aria-live="polite"></p><label for="rle-message">WhatsApp / mailto taslağı</label><textarea id="rle-message" rows="10" readonly></textarea><div class="actions"><a id="rle-whatsapp" class="button" rel="noopener noreferrer" target="_blank">WhatsApp'ta aç ↗</a><a id="rle-email" class="text-link">E-postada aç →</a></div><p class="small">“Talebi e-posta ile gönder” sunucuya iletir. WhatsApp bağlantısı tarayıcınızda açılır.</p></div><noscript><p>Form JavaScript olmadan da e-posta ile gönderilir. WhatsApp taslağı için JavaScript gerekir.</p></noscript></div>
<aside class="contact-card"><p class="eyebrow">DOĞRUDAN İLETİŞİM</p><h2>Birlikte netleştirelim.</h2><dl><dt>Telefon</dt><dd><?php foreach(rle_phones() as $phone): ?><a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/','',$phone)); ?>"><?php echo esc_html($phone); ?></a><br><?php endforeach; ?></dd><dt>E-posta</dt><dd><a href="mailto:<?php echo esc_attr($settings['email']); ?>"><?php echo esc_html($settings['email']); ?></a></dd><dt>Adres</dt><dd><?php echo esc_html($settings['address']); ?></dd></dl><p class="small">Ürün seçimi, model uygunluğu ve teklif kapsamı için iletişime geçin.</p><a class="text-link" href="<?php echo rle_link('firma-bilgilerimiz'); ?>">Firma bilgileri →</a></aside></section>
<?php elseif($route==='blog-sayfasi'): $posts=get_posts(array('post_type'=>'post','post_status'=>'publish','numberposts'=>-1,'orderby'=>'date','order'=>'DESC')); ?>
<section class="page-intro wrap rle-fade-in"><p class="eyebrow">RENTAL EKRAN / BİLGİ MERKEZİ</p><h1>LED ekran blogu.</h1><p>Teknoloji, proje seçimi ve operasyon konularında güncel içerikler; karar vermeden önce okumanız için derlendi.</p></section><section class="section wrap"><?php if(!$posts): ?><p>Yayında blog yazısı yok. Teknik rehberler menüden ulaşılabilir.</p><?php endif; ?><div class="blog-grid rle-stagger"><?php foreach($posts as $post): setup_postdata($post); $image=get_the_post_thumbnail_url($post,'large'); ?><article class="blog-card rle-reveal"><?php if($image): ?><img src="<?php echo esc_url($image); ?>" alt="<?php echo esc_attr(get_the_title($post)); ?>" loading="lazy" decoding="async"><?php else: ?><div class="blog-card-placeholder" aria-hidden="true"><span>LED</span></div><?php endif; ?><div><p class="eyebrow"><?php echo esc_html(get_the_date('j F Y',$post)); ?></p><h2><a href="<?php echo esc_url(get_permalink($post)); ?>"><?php echo esc_html(get_the_title($post)); ?></a></h2><p><?php echo esc_html(wp_trim_words(wp_strip_all_tags(get_the_excerpt($post) ?: $post->post_content),28)); ?></p><a class="text-link" href="<?php echo esc_url(get_permalink($post)); ?>">Yazıyı okuyun →</a></div></article><?php endforeach; wp_reset_postdata(); ?></div></section>
<?php elseif($route==='hakkimizda' || $route==='firma-bilgilerimiz'): $legacy=rle_legacy_content($route); ?>
<section class="page-intro wrap"><p class="eyebrow">RENTAL EKRAN / KURUMSAL</p><h1><?php echo esc_html($page['name']); ?></h1><p><?php echo esc_html($page['description']); ?></p></section><section class="section wrap corporate-layout"><div><?php foreach($legacy['sections'] as $section): ?><article><h2><?php echo esc_html($section['title']); ?></h2><?php foreach($section['text'] as $text): ?><p><?php echo esc_html($text); ?></p><?php endforeach; ?></article><?php endforeach; ?></div><aside class="contact-card"><p class="eyebrow">İLETİŞİM</p><h2>Rental Ekran</h2><p><?php echo esc_html($settings['address']); ?></p><p><?php foreach(rle_phones() as $phone): ?><a href="tel:<?php echo esc_attr(preg_replace('/[^+0-9]/','',$phone)); ?>"><?php echo esc_html($phone); ?></a><br><?php endforeach; ?><a href="mailto:<?php echo esc_attr($settings['email']); ?>"><?php echo esc_html($settings['email']); ?></a></p></aside></section><?php if(!empty($legacy['images'])): ?><section class="section wrap legacy-gallery"><div class="legacy-image-grid"><?php foreach($legacy['images'] as $image): ?><figure><img src="<?php echo esc_url($image['src']); ?>" alt="<?php echo esc_attr($image['alt']); ?>" loading="lazy"></figure><?php endforeach; ?></div></section><?php endif; ?>
<?php elseif(in_array($route,array('case-studies','shipment','partners','services'),true)): ?>
<section class="page-intro wrap"><p class="eyebrow">RENTAL EKRAN / BİLGİLER</p><h1><?php echo esc_html($page['name']); ?></h1><p><?php echo esc_html($page['description']); ?></p></section>
<?php require RLE_DIR.'templates/corporate.php'; ?>
<?php else: ?><article class="wrap guide-article"><header class="page-intro"><p class="eyebrow">RENTAL EKRAN / KARAR REHBERİ</p><h1><?php echo esc_html($page['name']); ?></h1><p><?php echo esc_html($page['description']); ?></p></header><?php require RLE_DIR.'templates/guides.php'; ?></article><div class="wrap"><?php rle_guides(); rle_cta(); ?></div><?php endif; ?>
<?php rle_render_shell_close(); ?>
